### ISSUE TITLE
Plumber workflow breaking after the approval stage with multiple times in same user login 

### ISSUE THREAD

**Issue by pyajamanam** [nathanwoulfe/Plumber#61] opened 2018-08-20 14:55 UTC
Hi Nathan,
stage 4 of 3 issue still exists,due to the multiple submit enabled in button drawer.
please find the attached url for workflow reproduced scenerio.

https://drive.google.com/file/d/1QpQwcROUz4XPb_lFsVNanwu-OaSCKCs8/view

**Comment by nathanwoulfe** [comment] 2018-08-20 20:34
Are you running the latest version? I haven't been able to replicate this on v0.9

**Comment by nathanwoulfe** [comment] 2018-08-21 00:31
Found the issue, will sort it.

**Comment by nathanwoulfe** [comment] 2018-08-21 02:13
Try this => https://ci.appveyor.com/api/buildjobs/c7h8xp2x48grfn27/artifacts/BuildPackage%2Fartifacts%2FPlumber_0.9.1-beta-000267.zip

Haven't released it yet, let me know if this resolves the issue (I've tested it, seems fine).

**Comment by pyajamanam** [comment] 2018-08-21 06:02
updated with new patch not able to add the comments,
tried appdata delete,plugins deleted and reinstalled.
installed the patch with new version 7.9.1


![image](https://user-images.githubusercontent.com/33079424/44383224-49c14080-a518-11e8-92ad-badf79a6e787.png)

**Comment by nathanwoulfe** [comment] 2018-08-21 06:40
Looks like a build issue - iconFilter is missing. Will have a look

**Comment by nathanwoulfe** [comment] 2018-08-21 08:02
What umbraco version are you on? I'm looking right now on the latest (7.12) and it's ok - found an unrelated issue, but the console is clear.

If you're on 7.9, I can't really support that with the latest releases, there's a lot of change in Umbraco between 7.9 and latest.

**Comment by nathanwoulfe** [comment] 2018-08-21 10:29
I've just run 0.9.2 against Umbraco 7.10 with no issues
Installing 7.11 now.

Per my comment on #60, 0.9 release will require at least Umbraco 7.10 and won't be backwards compatible with older versions.

**Comment by nathanwoulfe** [comment] 2018-08-21 10:40
Likewise on 7.11 -> v0.9.2 runs correctly, no errors logged anywhere

**Comment by nathanwoulfe** [comment] 2018-08-23 09:06
Rejection is a pretty complex mechanism, I'll need to have a proper look. There's a setting to allow/disallow editing content once it's in a workflow, which will impact on where the task bounces back to - if the content is locked it will need to go back to the start, otherwise it should go back to the previous group. Operative word there is should. Implicit/explicit shouldn't impact on this. 

Having said that, I have a feeling that rejecting will always send it back to the start, but resubmitting should go back to the rejecting group. Which makes sense as the rejection applies to the initial change, so should be returned to the initial editor. 

Like I said, will need to double check. 

Explicit/implicit works by either requiring all groups to approve the task (explicit) or skipping groups where the original change author is a member (implicit)

**Comment by pyajamanam** [comment] 2018-08-23 09:37
1.There is an issue i feel, if the final approve will do changes and publish,it is directly going to publish his changes and approved changes as well which is not recommended because final stage user chanegs need to be approved by someone.

2.**issues: deleted items always showing** 
https://drive.google.com/file/d/1WoQcsmR95y7pB18WjgFCAGjmaLQccj-i/view

**Comment by nathanwoulfe** [comment] 2018-08-23 09:47
1 - this is a business process. There is the option to lock content in a workflow to prevent edits, but (from memory) an admin user will always be able to edit content. Therefore, it's up to the site admin to determine how the workflow will be used. 

2 - is anything being logged in the browser console?

**Comment by pyajamanam** [comment] 2018-08-23 10:06
there is nothing logged in the console but if you can see the video attached,items are not removed after removing in content flow.

**Comment by nathanwoulfe** [comment] 2018-08-24 05:26
@pyajamanam - I can't reproduce the settings not saving. What version of Umbraco and Plumber are you using?

**Comment by blevai13** [comment] 2018-08-24 07:25
@nathanwoulfe,

In the ConfigService you have the GetPermissionForNode and there is an infinite loop. If all things are set  correctly one the conditions will be satisfied and it will quit from that loop, but if the node are deleted(Moved to Recycle bin) the loop never gonna end and the related sql query will be executed each time.

Definitely, I would say that needs to be reviewed, I'm not sure if it's happened because of some coincidence but all I can say you this was a problem on my project.

Thanks,
Botond

Thanks

**Comment by nathanwoulfe** [comment] 2018-08-24 07:47
That makes sense - an earlier version enforced setting a default group, which would have prevented that from happening. I removed that a few versions back, but obviously didn't consider deleted nodes. Should be easy enough to sort.

**Comment by nathanwoulfe** [comment] 2018-08-25 01:54
@blevai13 pretty sure this will be resolved by fixing #67 - by not including trashed nodes in the workflow response, it won't hit the call to check permissions, so no more issue.

**Comment by pyajamanam** [comment] 2018-09-04 05:33
Hi Nathan,
Just curious of asking this question.
can i know what is the major responsibility of event-handlers in workflow.also can you please let  me know email functionality will work just by giving email address in settings else do i need to configure  smtp service.

Thanks,Pradeep

**Comment by nathanwoulfe** [comment] 2018-09-04 07:48
The event handlers don't do anything out of the box - they're simply there as extension points if you wanted to hook into the event (similar to how you would the ones in Umbraco core).

Email will need to be configured on your server for notifications to send, but all that is needed in Plumber settings is the email and site url fields.

**Closed** 2019-05-04 00:53 UTC
