### ISSUE TITLE
Offline Approval of edits (approver not logged in to back office)

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [nathanwoulfe/Plumber#105] opened 2019-03-05 16:52 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Plumber version**
Which version of Plumber does the bug occur in?

**Additional context**

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-05 17:11
Using Plumber 1.1.5  with Umbraco 7.12.3. Not browser specific.

In order to preview pages when not logged into the backend CMS, we have applied : <add key="owin:appStartup" value="WorkflowOwinStartup" /> // replaces 'UmbracoStandardOwinStartup' \ 
 according to: https://github.com/nathanwoulfe/Plumber/blob/master/Workflow/DOCS.md

The issue is that the link in the subsequent email returns a 404 error. "Offline approval is permitted for this change (no login required)." Clicking on the link  'offline approval' returns the error.

"This umbdev-upgrade page can’t be found No web page was found for the web address: 
eg://umbraco/workflow-preview/21380/21/347/7dfad456-a334-4a25-a732-f9b79e859138

We think that we've set everything up correctly - what have we missed?

regards Fiona

**Comment by nathanwoulfe** [comment] 2019-03-07 03:44
Hi Fiona, to be honest, I haven't looked at this feature in ages, and I'm not entirely confident it ever worked perfectly...

Looks like the routing isn't working for the offline/preview view, I'll have a dig and see what I can find. From memory, it was a fairly hacky implementation, so highly likely it died somewhere between the Umbraco version I initially targeted, and the latest releases...

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-07 08:45
Ah ok! Our web site editors are really looking forward to using this feature, as it solves a lot of problems. 
It would be great if you were able to have a dig around and get it working.
thanks Fiona

**Comment by nathanwoulfe** [comment] 2019-03-08 23:34
I've checked this on 7.12.2 using v1.1.6 and it works correctly, albeit with a javascript error that I'll need to fix. As I'm sure you'd appreciate, it's difficult to debug this when it's likely related to something specific to your site.

Just noticed your example URL, it has /umbraco/ as the first segment - that's probably the cause. The URL in the email should be /domain/workflow-preview/nodeid/userid/taskid/workflowguid.

Can you share your settings from the workflow backoffice section? Feels like it's to do with the base URL for the edit site. Are links in other notification emails working?

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-11 14:58
Hi Nathan – thanks for the ideas.

We are currently testing this in a dev environment, so our settings may be the problem. But – we do not use a sub-domain for email notifications. Instead we use http://historicengland.org.uk/umbraco/.


[cid:image001.png@01D4D819.E7B11070]
That url works fine for on-line approval of workflow notifications.

Strangely, the offline approval link does work if the page has already been approved ( we have more than one admin editor who can approve pages - …..we have a lot of ‘every-day’ editors).

Regards Fiona

**Comment by nathanwoulfe** [comment] 2019-03-14 01:27
Try setting the email config to http://historicengland.org.uk, I'd say include the /umbraco/ segment will be causing issues. Maybe.

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-14 10:05
Thanks Nathan.


We’ll try that and let you know how we get on.

Regards Fiona

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-14 14:30
Hi Nathan - good news is that your suggestion about the email config worked.  Thanks.
'Bad' news is that the image showing the page that needs to be approved is so small than an approver cannot see enough detail to be able to decide whether or not to reject/approve.

I cannot adjust the line below the page / above the reject/approve buttons to resize view.

Viewed using Chrome v72.0.3626 on desktop; IE11 desktop and Firefox v65

![image](https://user-images.githubusercontent.com/22772250/54364625-2ea95000-4665-11e9-9e58-4097b32957ba.png)

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-14 14:48
Further feedback: when clicking either the reject, or the approve button, - a right-hand pane appears, but hangs (does not load)

**Comment by nathanwoulfe** [comment] 2019-03-14 23:41
This is resolved in the next patch release (v1.1.7), which should be out in a few days - just waiting on a pending bug report which I'd like to include in the release.

In the meantime, the nightly build is available here => https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/artifacts, and has the fix for this. Feel free to give it a try, or just wait on the 1.1.7 release.

N

**Comment by HistoricEnglandDigitalTeam** [comment] 2019-03-15 09:25
Thank Nathan. Looking forward to it!

**Closed** 2019-05-04 00:54 UTC
